"""fix habits unique constraint to per user

Revision ID: 143baf2f7d49
Revises: 4151e4d639c0
Create Date: 2026-05-16 01:27:55.096666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '143baf2f7d49'
down_revision: Union[str, Sequence[str], None] = '4151e4d639c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('habits_name_key'), 'habits', type_='unique')
    op.create_unique_constraint(None, 'habits', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'habits', type_='unique')
    op.create_unique_constraint(op.f('habits_name_key'), 'habits', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
