"""add unique constraint

Revision ID: 4151e4d639c0
Revises: bf04dfa38564
Create Date: 2026-05-07 01:18:03.869362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4151e4d639c0'
down_revision: Union[str, Sequence[str], None] = 'bf04dfa38564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'habits', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'habits', type_='unique')
    # ### end Alembic commands ###
