"""add nullable constraints and cascade deletes

Revision ID: bf04dfa38564
Revises: 9f191103c2b6
Create Date: 2026-05-05 18:25:35.901081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf04dfa38564'
down_revision: Union[str, Sequence[str], None] = '9f191103c2b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_logs', 'habit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('activity_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('activity_logs', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('activity_logs', 'count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('activity_logs_user_id_fkey'), 'activity_logs', type_='foreignkey')
    op.drop_constraint(op.f('activity_logs_habit_id_fkey'), 'activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'activity_logs', 'habits', ['habit_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'activity_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('habits', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('habits', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('habits', 'color',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('habits', 'created_at',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_constraint(op.f('habits_user_id_fkey'), 'habits', type_='foreignkey')
    op.create_foreign_key(None, 'habits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'habits', type_='foreignkey')
    op.create_foreign_key(op.f('habits_user_id_fkey'), 'habits', 'users', ['user_id'], ['id'])
    op.alter_column('habits', 'created_at',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('habits', 'color',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('habits', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('habits', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.create_foreign_key(op.f('activity_logs_habit_id_fkey'), 'activity_logs', 'habits', ['habit_id'], ['id'])
    op.create_foreign_key(op.f('activity_logs_user_id_fkey'), 'activity_logs', 'users', ['user_id'], ['id'])
    op.alter_column('activity_logs', 'count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('activity_logs', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('activity_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('activity_logs', 'habit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
